FROM jasonbean/guacamole

#ssh 协议中文支持
RUN apt-get update                                                                                                                              && \
    apt-get install -y --no-install-recommends fonts-wqy-microhei                                                                            && \
    rm -rf /var/lib/apt/lists/*