#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
    "${SSP_PATH}"

# install app
if [ ! -e "${SSP_PATH}/index.php" ]; then
	tar xf /app/ssp.tar.gz -C \
		"${SSP_PATH}" --strip-components=1
fi