## -*- docker-image-name: "frp-client" -*-
FROM alpine:latest

ENV VERSION 0.19.1
ENV FRP_PACKAGE frp_${VERSION}_linux_amd64

COPY $FRP_PACKAGE/frpc /
COPY $FRP_PACKAGE/frpc.ini /

WORKDIR /
CMD ["/frpc" ,"-c", "frpc.ini"]

#下载并解压
# RUN wget https://github.com/fatedier/frp/releases/download/v${VERSION}/$FRP_PACKAGE && tar -xzf $FRP_PACKAGE && rm $FRP_PACKAGE
