## -*- docker-image-name: "frp-server" -*-
FROM alpine:latest

ENV VERSION 0.19.1
ENV FRP_PACKAGE frp_${VERSION}_linux_amd64

COPY $FRP_PACKAGE/frps /
COPY $FRP_PACKAGE/frps.ini /

WORKDIR /
CMD ["/frps" ,"-c", "frps.ini"]
