#!/bin/bash

chmod 1777 /tmp/.X11-unix

	Xorg\
	  +extension RANDR\
	  +extension RENDER\
	  -config /etc/xpra/xorg.conf\
	  -dpi $XORG_DPI\
	  -logfile /tmp/Xorg.log\
	  -nolisten tcp\
	  -noreset\
	  -xinerama &

su-exec "${UNAME}" bash tcp_m "$@"


