FROM node:8-alpine
RUN mkdir app
WORKDIR app
ADD package.json /app
RUN npm i

ADD . /app

ENV VERSION 3.5.5
RUN wget https://github.com/liuzhuoling2011/baidupcs-web/releases/download/${VERSION}/BaiduPCS-Go-${VERSION}-linux-64 \
&& mv BaiduPCS-Go-${VERSION}-linux-64 BaiduPCS-Go \
&& chmod u+x baidupcs

CMD [ "npm", "start" ]
