#!/usr/bin/with-contenv bash

# copy config
[[ ! -f /config/.config.php ]] && cp \
	/defaults/.config.example.php /config/.config.php

[[ ! -f /config/appprofile.php ]] && cp \
	/defaults/appprofile.example.php /config/appprofile.php

[[ -d ${SSPANEL_UIM_PATH}/config ]] && rm -rf ${SSPANEL_UIM_PATH}/config
ln -s /config ${SSPANEL_UIM_PATH}/config

# create admin if admin name not exsit
php xcat User createAdmin << EOF
${ADMIN_NAME}
${ADMIN_PASSWORD}
y
EOF

# download ip db
php xcat Tool initQQWry || echo "php xcat Tool initQQWry command error"
# download all proxy clients
php xcat ClientDownload || echo "php xcat Cli command error"