#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
    "${SSPANEL_UIM_PATH}"

# install app
if [ ! -e "${SSPANEL_UIM_PATH}/index.php" ]; then
	tar xf /app/ssp.tar.gz -C \
		"${SSPANEL_UIM_PATH}" --strip-components=1
fi