#!/usr/bin/with-contenv bash

# copy config
[[ ! -f /config/nut.conf ]] && cp \
  /defaults/nut.default.conf /config/nut.conf

[[ ! -f /config/users.conf ]] && cp \
  /defaults/users.conf /config/users.conf

[[ -f /app/nut/conf/nut.conf]] && rm /app/nut/conf/nut.conf
ln -s /config/nut.conf /app/nut/conf/nut.conf
[[ -f /app/nut/conf/users.conf]] && rm /app/nut/conf/users.conf
ln -s /config/users.conf /app/nut/conf/users.conf